### ISSUE TITLE
Road to browser support

### ISSUE THREAD

**Issue by mkg20001** [ZeroNetJS/zeronet-js#90]
# Tracking events related to ZeroNetJS Browser Support

**Comment by mkg20001** [comment]
## Service Workers can be used as proxys. Meaning we can put a FULL zeronet node IN THE BROWSER with an UI SERVER :tada: 

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by mkg20001** [comment]
## Updates:
 - ### The swarms are separated
    Makes a lot of things easier
 - ### Browser & Client now have websocket-star support
   Which means that the browser now finally could (just in theory for now) download zites from other websocket-star peers

**Comment by Plasmmer** [comment]
I think this https://github.com/ZeroNetJS/zeronet-js/issues/46 issue is important here.

**Comment by mkg20001** [comment]
> I think this #46 issue is important here.

It's not directly related

**Comment by mkg20001** [comment]
## ToDos for downloading files:
 - [ ] Rewrite discovery and peer classes to support libp2p and "hasZite" command
 - [ ] Finish "get zites" stuff
 - [ ] Implement fileGet into zeronet-fileserver
 - [ ] Finish libp2p-websocket-star

### Post-Goals:
 - [ ] Multi-User

That's it. If we are done with every goal then stuff like commenting extensions will be possible.

**Comment by mkg20001** [comment]
![](https://user-images.githubusercontent.com/7735145/30240035-bc0f4012-9568-11e7-8e63-7579a6b7012f.png)
znjs in the browser connects to znjs :tada:
